#!/bin/sh
set -ue
OUTPUT_DIR=${OUTPUT_DIR:-$HOME/.config/$(basename $(pwd))}
DURATION=${DURATION:-1d}
CA_NAME=${CA_NAME:-keymaster.pem}
SUBJECT=${SUBJECT:-winexec_client}

echo Updating $SUBJECT certificates in $OUTPUT_DIR
mkdir -p $OUTPUT_DIR
(
    cd $OUTPUT_DIR
    mkcert --force --chain $CA_NAME
    mkcert --force $SUBJECT --duration $DURATION
    ls -lt
)
